name: Astro Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno para GitHub Pages
        run: echo "GITHUB=true" >> $GITHUB_ENV

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'

      - name: Instalar dependencias
        run: npm install

      - name: Generar el sitio Astro
        run: npm run build

      - name: Mover los archivos generados a docs/
        run: mv dist docs

      - name: Confirmar los archivos generados
        run: ls -la docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Agregar y subir cambios a GitHub Pages
        run: |
          git add docs/
          git commit -m "Desplegar nueva versión en GitHub Pages"
          git push origin main
